dist: trusty
sudo: required

language: java
jdk: openjdk8

before_install:
- sudo wget https://github.com/brendanmanning/SketchadelphiaServer/blob/master/assets/PhillyCrimeDataIncidents.csv?raw=true -O /root/PhillyCrimeDataIncidents.csv
- cd java